### PR TITLE
Fix default command line arguments and uniformize across CLI

### PR DESCRIPTION
**Pull request by gdevenyi**
Addresses #58

### CODE REVIEW

**Comment by gdevenyi** [comment]
hold off on this, I'm going to copy all the defaults from the GUI which I presume is the tested and default configuration

**Comment by gdevenyi** [comment]
This fixes inconsistencies with the command line, however, there are still internal inconsistencies between the GUI, CLI, and the defaults setup ini __init__ of the conversion code. The only solution I see for the CLI is a rewrite with better names for the options, which would be a breaking change, so I leave it for now.

**Comment by SebastianoF** [comment]
Thanks! Had to do some changes to your PR to resolve some conflicts, as in the meantime I had made some modification of the codebase.

As you pointed out there is some duplicate code between CLI and GUI. Do you want to solve this creating a new python module with the common logic?

**Comment by gdevenyi** [comment]
Ref #58

**Pull request merged**
