### PR TITLE
Allow spaces in directory paths

### PR DESCRIPTION
**Pull request by jathpala**
Hi,

I have a small modification that you might find helpful.

The current implementation uses an os.system call to the native shell mkdir function when creating new folders in converter.py. The way this is implemented causes problems for directory paths that include spaces in the name.

This pull request replaces calls to os.system with os.makedirs which gets around this limitation.

The remainder of the code changes are actually just to the test suite.

I'm not entirely sure what test_warning_banana_bad_n() tests but I believe it is for trying to create an output folder when one already exists? If so, then the method of testing the assertion changes with the use of os.makedirs. An appropriate modification has been made.

Another test suite called test_convert_banana_spaces.py has been added. It is essentially a copy of test_convert_banana.py but uses 'bru banana' and 'nifti banana' (with spaces) as the paths to be used. The 'bru banana' folder is just a direct copy of the original 'bru_banana' folder. This test suite passes with this commit but fails on the original implementation.

Let me know your thoughts.

Thanks,

Jath

### CODE REVIEW

**Comment by SebastianoF** [comment]
Hi Jath!

Thanks for considering helping the development of bruker2nifti, much much appreciated!
Only, I think there are still some improvements to do before the merge.

+ About giving the user the possibility of having paths with spaces, can you please add a warning to console (with a print, or with the more sophisticated [logme](https://docs.pipenv.org/en/latest/basics/) or similar) when there are spaces, and stop the conversion? Most of the software in the post-processing are not permissive to this extent, so it is a practice that I would not like to encourage: it can simplify the life for the conversion step, but the user may need to remove the spaces from the paths manually afterwards anyway.
Or maybe adding the typical pop up question: `Are you sure do you want to continue [Y/n]?` Or maybe even removing the spaces automatically: `There are spaces in the input paths. These will be replaced with underscores. Do you want to continue [Y/n]?` (or similar). What do you think?

+ For the extra test module and the extra data test, I would like to keep the code as minimal as possible and avoid redundancies. It is already not best practice to have data test in the repo itself (in a future version I should better distinguish between unittests -no data and only [mock](https://medium.com/@yeraydiazdiaz/what-the-mock-cheatsheet-mocking-in-python-6a71db997832)- and a more comprehensive integration test - with data cloned from bruker2nifti_qa repo). This difference was not clear to me when I wrote this code, and it would greatly improve maintainability and efficiency. For your case, can you for example mock some data input path and do unittest of only the function that reads and creates the path with spaces, ensuring the warning is thrown, without considering a full copy of the dataset only for a single test case?

+ It is a good idea to move to pipenv, as it is going to be the future standard for production. At the same time, there may be some issues in installing this particular tool in development mode (`pip install -e .` is the usual way for research code, and especially this one, that needs still a lot of tweaks - see open issues!). About pipenv, I still do not know how to keep the `pipfile` and the `requirements.txt` coherent. Is there any "translator" to keep both files in sync automatically, to allow the user to install with the old pip? Any suggestion is more than welcome!

+ [For what I can understand](https://docs.pipenv.org/en/latest/basics/) it is better to add the ignore the `pipfile.lcok` for code that is targeting more than one python version.

+ For what I remember, nosetest is almost not maintained anymore. Is it still the case? If yes, I would suggest using pytest instead (nosetest had been "recently" purged from the repo - see commit tagged "Nosetests is no more"), or only assert, to have the minimal amount of dependencies as possible.

...I know I am in your way for the merge and I'm asking you a lot...! On the top, this repo is far from being perfect under many perspective, and in particular in term of testing. At the same time I really do not want your efforts to be wasted in merging your work now and then having to delete part of it in the subsequent attempt of improving the testing structure and removing the data from the repo. 

Thanks for your help again!
Sebastiano

P.S. An AUTHORS file is on its way. As soon as done, please pull the repo and add your name in the next PR.

**Comment by jathpala** [comment]
Hi Sebastiano,

Thanks for the feedback.

> ...I know I am in your way for the merge and I'm asking you a lot...! 

Firstly, not at all! I'd much rather you merge good code that fits the code base than something half-baked!

> About giving the user the possibility of having paths with spaces, can you please add a warning to console (with a print, or with the more sophisticated logme or similar) when there are spaces, and stop the conversion?

Yes I think that's a good idea. I think printing a message to the console is probably the best way of doing it so I'll add the relevant code.

> For the extra test module and the extra data test, I would like to keep the code as minimal as possible and avoid redundancies.
> I would suggest using pytest 

Yes actually I'd be very happy to use pytest instead. Sorry I got the impression you were using nosetest which is why I used it but that's easily fixed. In terms of keeping the test suite small, I could, yes I agree it makes sense to just mock a file path with spaces rather than have redundant test data. I'll make the necessary changes.

> About pipenv, I still do not know how to keep the pipfile and the requirements.txt coherent. Is there any "translator" to keep both files in sync automatically, to allow the user to install with the old pip?
> For what I can understand it is better to add the ignore the pipfile.lcok for code that is targeting more than one python version.

Sorry I added pipenv for managing the virtual environment as much as anything. If you wanted I could remove the pipenv sutff and just use virtualenv/venv  for the virtual environment and leave requirements.txt. Alternatively if we did keep the pipfile running `pipenv run pip freeze > requirements.txt` would update requirements.txt to match the current pipfile.lock. I think you're right about keeping it out of git if supporting both python 2 and python 3. I'll add it to gitignore.

Thanks again for the feedback. I'll get working on the changes and update the pull request in a little while.

Cheers,
Jath

**Comment by SebastianoF** [comment]
Great!
Agree with all.
Please do keep pipenv alongside the old fashion requirements.txt!
Thanks, looking forward for the next PR!

**Comment by jathpala** [comment]
Oh oh... I think I messed up my git foo. I could spend the next 10 hours trying to work out what I messed up and how to fix it but I think it'll be easier for me to just close this and reopen a new pull request. I will combine the multiple commits to a simple commit as well to make the merge cleaner.

**Pull request closed without merging**
